version: '2'
services:
  neo4j:
    image: richogtz/neo4j-apoc:4.0.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/conf:/conf
    environment:
      - NEO4J_dbms_security_procedures_unrestricted="apoc.*"
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/test
  golang:
    depends_on:
      - neo4j
    build: ./go
    image: richogtz/go-dev
    container_name: golang
    volumes:
      - /Users/luisricardogutierrez/Documents/my_projects/Wineops:/go/src/github.com/RichoGtz23/Wineops
    ports:
      - "8080:8080"
